services:
  emerald_asp:
    build:
      context: .
    ports:
      - 5000:80
    depends_on:
      - emerald_mongodb
    environment: 
      Mongo__ConnectionString: "mongodb://root:rootpassword@emerald_mongodb:27017/emerald?authSource=admin"
      Mongo__DatabaseName: "emerald"

  emerald_mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: