version: '3.4'

services:
  emerald.application:
    image: ${DOCKER_REGISTRY-}emeraldapplication
    build:
      context: .
      dockerfile: Emerald.Application/Dockerfile
    ports:
    - 812:80
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: