version: '3.4'

services:
  emerald.application:
    image: ${DOCKER_REGISTRY-}emeraldapplication
    build:
      context: .
      dockerfile: Emerald.Application/Dockerfile
    ports:
    - 811:80
      
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: