version: '3.4'

services:
  emerald.application:
    image: ${DOCKER_REGISTRY-}emeraldapplication
    build:
      context: .
      dockerfile: Emerald.Application/Dockerfile
    ports:
      - 812:80
    depends_on:
      - mongo
    environment: 
      Mongo__ConnectionString: "mongodb://mongo:27017/emerald"
      Mongo__DatabaseName: "emerald"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: