version: '3.4'

services:
  emerald.application:
    image: ${DOCKER_REGISTRY-}emeraldapplication
    build:
      context: .
      dockerfile: Emerald.Application/Dockerfile
    ports:
      - 812:80
    depends_on:
      - mongo
    environment: 
      Mongo__ConnectionString: "mongodb://mongo:27017/emerald"
      Mongo__DatabaseName: "emerald"
      Jwt__Key: "bqT4%vB7&cJgT5rpV*H6H%#@qsds^-93@y*6fCw#&UsZmZEXL@d8R*^DaUMgS4!X"
      KissLog__OrganizationId: "KissLog.OrganizationId=9c5fee9c-056f-4c13-bee5-3b9689d01ac6"
      KissLog__ApplicationId: "KissLog.ApplicationId=fc4be889-6d7d-4625-bd0c-5a917a97d94d"
      KissLog__ApiUrl: "KissLog.ApiUrl=https://api.kisslog.net"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: